"""Add email_notifications field to User model

Revision ID: 140168af89d2
Revises: bac645abdba4
Create Date: 2025-10-04 19:07:57.036729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '140168af89d2'
down_revision = 'bac645abdba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_notifications', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email_notifications')

    # ### end Alembic commands ###
