"""Add is_admin field to User model

Revision ID: 1966d08cc9cb
Revises: e84dbc6dacf4
Create Date: 2025-09-24 22:45:59.984547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1966d08cc9cb'
down_revision = 'e84dbc6dacf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_column('minimum_overlap_hours')
        batch_op.drop_column('description')

    with op.batch_alter_table('group_availability_alert', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_group_availability_alert'), type_='unique')
        batch_op.create_unique_constraint('unique_group_date_alert', ['group_id', 'date'])
        batch_op.drop_column('start_time')
        batch_op.drop_column('end_time')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('group_availability_alert', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', sa.VARCHAR(length=5), nullable=False))
        batch_op.add_column(sa.Column('start_time', sa.VARCHAR(length=5), nullable=False))
        batch_op.drop_constraint('unique_group_date_alert', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('unique_group_availability_alert'), ['group_id', 'date', 'start_time', 'end_time'])

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('minimum_overlap_hours', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
