"""Add DefaultSchedule model for saving schedule templates

Revision ID: 209bab16ae14
Revises: 7740a5ff04cf
Create Date: 2025-09-19 18:50:59.730918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '209bab16ae14'
down_revision = '7740a5ff04cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('default_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('schedule_name', sa.String(length=100), nullable=False),
    sa.Column('schedule_data', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('default_schedule')
    # ### end Alembic commands ###
