"""Add external calendar event IDs to Event model

Revision ID: 55d02cc5e29d
Revises: d6fd6cbd594d
Create Date: 2025-10-16 11:21:58.408781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55d02cc5e29d'
down_revision = 'd6fd6cbd594d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_calendar_event_ids', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('outlook_calendar_event_ids', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('outlook_calendar_event_ids')
        batch_op.drop_column('google_calendar_event_ids')

    # ### end Alembic commands ###
