"""Add Outlook Calendar integration

Revision ID: 59bca500f2ba
Revises: 604864ef1f98
Create Date: 2025-09-30 19:48:47.637661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59bca500f2ba'
down_revision = '604864ef1f98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outlook_calendar_sync',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('outlook_calendar_id', sa.String(length=255), nullable=True),
    sa.Column('encrypted_refresh_token', sa.Text(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('sync_enabled', sa.Boolean(), nullable=True),
    sa.Column('auto_sync_availability', sa.Boolean(), nullable=True),
    sa.Column('auto_add_events', sa.Boolean(), nullable=True),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outlook_calendar_sync', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outlook_calendar_sync_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('outlook_calendar_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('outlook_calendar_enabled')

    with op.batch_alter_table('outlook_calendar_sync', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outlook_calendar_sync_created_at'))

    op.drop_table('outlook_calendar_sync')
    # ### end Alembic commands ###
