"""Add location field to Event model

Revision ID: 604864ef1f98
Revises: b2836da99544
Create Date: 2025-09-30 19:17:22.334361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '604864ef1f98'
down_revision = 'b2836da99544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
