"""Add EventInvitation model for event invitations

Revision ID: 6475f900e1ca
Revises: 89d2b0bace08
Create Date: 2025-09-19 14:10:12.770760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6475f900e1ca'
down_revision = '89d2b0bace08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_invitation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('invitee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['invitee_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_invitation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_invitation_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('event_invitation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_invitation_created_at'))

    op.drop_table('event_invitation')
    # ### end Alembic commands ###
