"""Add Google Calendar integration models

Revision ID: 7740a5ff04cf
Revises: 6475f900e1ca
Create Date: 2025-09-19 14:23:50.269077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7740a5ff04cf'
down_revision = '6475f900e1ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_calendar_sync',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('google_calendar_id', sa.String(length=255), nullable=True),
    sa.Column('encrypted_refresh_token', sa.Text(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('sync_enabled', sa.Boolean(), nullable=True),
    sa.Column('auto_sync_availability', sa.Boolean(), nullable=True),
    sa.Column('auto_add_events', sa.Boolean(), nullable=True),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('google_calendar_sync', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_google_calendar_sync_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_calendar_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('timezone')
        batch_op.drop_column('google_calendar_enabled')

    with op.batch_alter_table('google_calendar_sync', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_google_calendar_sync_created_at'))

    op.drop_table('google_calendar_sync')
    # ### end Alembic commands ###
