"""Add weekly_reminders field to User model

Revision ID: d6fd6cbd594d
Revises: 140168af89d2
Create Date: 2025-10-04 19:14:33.536899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6fd6cbd594d'
down_revision = '140168af89d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weekly_reminders', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('weekly_reminders')

    # ### end Alembic commands ###
