"""Add SMS notifications preference to User model

Revision ID: fc5d5a43e365
Revises: 120ee4aba0b3
Create Date: 2025-09-15 22:37:32.025104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc5d5a43e365'
down_revision = '120ee4aba0b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sms_notifications', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('sms_notifications')

    # ### end Alembic commands ###
